== Circle

=== circle

[source,scheme]
----
(circle)
----

Constructs a circle instance. Circle has the following properties (each of which can be either a value, or a function of data)

* id - item id. Can be anything. Defaults to `#f`.
* x - circle's center x position. Defaults to 0.
* y - circle's center y position. Defaults to 0.
* radius - circle's radius. Defaults to 100.
* inner-radius - circle's inner radius. If greater than 0 it becomes a donut. Defaults to 0.
* start-angle - circle's slice start angle in degrees. Defaults to 0.
* end-angle - circle's slice end angle in degrees. Defaults to 360.
* fill - color to fill cirle. Either instance of color, or #f. Defaults to `(color 200 100 100)`.
* stroke - color to stroke circle border. Either instance of color, or #f. Defaults to `(color 10 10 10)`.
* stroke-width - width of stroke. Defaults to 1.
* segments - segment count for rendering the circle. Higher count will make circle smoother. Defaults to 20.

Example 

[source,scheme]
----
(circle #:x 50
        #:y 50
        #:fill (color 255 0 0))
----

=== circle-o

[source,scheme]
----
(circle-o)
----

Constructs a circle instance, similar to `circle`. Difference, however, is that the defaults for all properties are `#f` instead. Intended to be used with overriding, see `override-circle`.


=== circle?

[source,scheme]
----
(circle? c)
----

Returns #t if `c` is a circle, #f otherwise.

=== override-circle

[source,scheme]
----
(override-circle circle-item circle-override)
----

Overrides properties in circle `circle-item` with those circle's `circle-override` properties that are not #f. If properties in `circle-override` are given as functions, the supplied parameter is not datum as usual, but the corresponding property value from `circle-item`. If the property in `circle-item` was a procedure, the overring method is called during data application call.

Exmaple

[source,scheme]
----
(define circleA (circle #:fill (color 255 0 0)))
(define circleOverride (circle-o #:fill (color 0 255 0)))
(define overridenCircle (override-circle circleA circleOverride))
(equals? overridenCircle (circle #:fill (color 0 255 0))) ;should be true
----
